/**
 * Generated by Aster
 */
package org.apache.commons.compress.archivers.zip;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_ZipMethod_Test_Passing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testGetMethodByCodeForStored_ZavV0() {
    assertEquals(ZipMethod.STORED, ZipMethod.getMethodByCode(ZipMethod.STORED.getCode()));
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testGetCodeForStored_Oysl0() {
    ZipMethod zipMethod = ZipMethod.STORED;
    int expectedCode = 0; // Assuming the code for STORED is 0
    assertEquals(expectedCode, zipMethod.getCode());
}
}