/**
 * Generated by Aster
 */
package org.apache.commons.jxpath;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;
import java.util.concurrent.TimeUnit;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_JXPathContextFactoryConfigurationError_Test_Failing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testGetMessageWithException_TssF0_fid1() {
    Exception e = new Exception("Exception message");
    JXPathContextFactoryConfigurationError error = new JXPathContextFactoryConfigurationError(e);
    assertEquals("Exception message", error.getMessage());
}
}