/**
 * Generated by Aster
 */
package org.apache.commons.jxpath;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;
import java.util.concurrent.TimeUnit;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_JXPathException_Test_Failing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testGetMessageWithOnlyThrowable_GgOu2() {
        Throwable cause = new Throwable("java.lang.Throwable: Cause message; Cause message");
        JXPathException ex = new JXPathException(cause);
        assertEquals("java.lang.Throwable: Cause message; Cause message", ex.getMessage());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testGetMessageWithOnlyThrowable_GgOu2_fid1() {
        Throwable cause = new Throwable("Cause message");
        JXPathException ex = new JXPathException(cause);
        assertEquals("Cause message", ex.getMessage());
    }
}