/**
 * Generated by Aster
 */
package org.apache.commons.compress.archivers.sevenz;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_DeltaDecoder_Test_Passing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testGetOptionsAsPropertiesWithIntegerInput_VYqi0() throws Exception {
    DeltaDecoder decoder = new DeltaDecoder();
    Object options = 2;
    byte[] expected = new byte[] {1};
    byte[] result = decoder.getOptionsAsProperties(options);
    assertArrayEquals(expected, result);
}
}