/**
 * Generated by Aster
 */
package org.apache.commons.compress.archivers.sevenz;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import javax.crypto.spec.SecretKeySpec;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_AES256Options_Test_Passing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testNewSecretKeySpecWithValidInput_ENYJ0_1() {
    byte[] keyBytes = new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
    SecretKeySpec result = AES256Options.newSecretKeySpec(keyBytes);
    assertNotNull(result);}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testNewSecretKeySpecWithValidInput_ENYJ0_2() {
    byte[] keyBytes = new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
    SecretKeySpec result = AES256Options.newSecretKeySpec(keyBytes);
    assertEquals("AES", result.getAlgorithm());}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testNewSecretKeySpecWithValidInput_ENYJ0() {
    byte[] keyBytes = new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
    SecretKeySpec result = AES256Options.newSecretKeySpec(keyBytes);
    assertNotNull(result);
    assertEquals("AES", result.getAlgorithm());
}
}