/**
 * Generated by Aster
 */
package org.apache.commons.jxpath.servlet;
import java.util.Enumeration;
import javax.servlet.jsp.PageContext;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;
import java.util.concurrent.TimeUnit;
import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import org.mockito.InjectMocks;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;   
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class ASTER_PageScopeContext_Test_Failing {
@Mock
    private PageContext pageContext;
@InjectMocks
    private PageScopeContext pageScopeContext;
@Mock
    private Enumeration<String> attributeNames;
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testGetAttributeNames_EuIU0_fid2() {
    PageContext mockPageContext = mock(PageContext.class);
    Enumeration<String> expectedAttributes = Collections.enumeration(Arrays.asList("attr1", "attr2", "attr3"));
    when(mockPageContext.getAttributeNamesInScope(PageContext.PAGE_SCOPE)).thenReturn(expectedAttributes);
    PageScopeContext pageScopeContext = new PageScopeContext(mockPageContext);
    Enumeration<String> result = pageScopeContext.getAttributeNames();
    List<String> resultList = Collections.list(result);
    List<String> expectedList = Collections.list(expectedAttributes);
    assertEquals(expectedList, resultList);
}
}