/**
 * Generated by Aster
 */
package org.apache.commons.compress.compressors.pack200;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_Pack200CompressorInputStream_Test_Passing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testResetOnPack200CompressorInputStream_LhYB0() throws IOException {
    File tempFile = File.createTempFile("test", ".pack");
    Pack200CompressorInputStream inputStream = new Pack200CompressorInputStream(tempFile);
    inputStream.mark(100); // Assuming mark is supported and set before reset
    inputStream.reset();
    assertTrue(inputStream.available() > 0); // Check if stream is reset to the marked position
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testMatches_IncorrectSignature_Yrft1_KNHN0() {
    byte[] signature = {(byte) 0xCA, (byte) 0xFE, (byte) 0xDA, (byte) 0x0E};
    int length = 4;
    assertFalse(Pack200CompressorInputStream.matches(signature, length));
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testMatches_ShorterLength_vLxv2_SWNu0() {
    byte[] signature = {(byte) 0xCA, (byte) 0xFE};
    int length = 2;
    assertFalse(Pack200CompressorInputStream.matches(signature, length));
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testCloseWithFileAndProperties_fPXB1_WIbT0() throws IOException {
    File tempFile = File.createTempFile("test", ".pack");
    tempFile.deleteOnExit();
    HashMap<String, String> properties = new HashMap<>();
    Pack200CompressorInputStream pack200CompressorInputStream = new Pack200CompressorInputStream(tempFile, properties);
    pack200CompressorInputStream.close();
    assertTrue(tempFile.exists(), "File should still exist");
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testAvailable_wBpD0_fid2() throws IOException {
    File tempFile = File.createTempFile("test", ".pack");
    Pack200Strategy strategy = Pack200Strategy.TEMP_FILE;
    Map<String, String> properties = new HashMap<>();
    properties.put("key", "value");
    Pack200CompressorInputStream pack200CompressorInputStream = new Pack200CompressorInputStream(tempFile, strategy, properties);
    int expectedAvailable =29; // Assuming the file is empty and thus no data available
    int actualAvailable = pack200CompressorInputStream.available();
    assertEquals(expectedAvailable, actualAvailable);
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testSkipMethod_ynpT0_fid2() throws IOException {
    File testFile = File.createTempFile("test", ".pack200");
    testFile.deleteOnExit();
    Pack200Strategy strategy = Pack200Strategy.IN_MEMORY;
    Map<String, String> properties = new HashMap<>();
    Pack200CompressorInputStream pack200CompressorInputStream = new Pack200CompressorInputStream(testFile, strategy, properties);
    long skipAmount = 100L;
    long skippedBytes = pack200CompressorInputStream.skip(skipAmount);
    assertTrue(skippedBytes <= skipAmount);
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testMatches_ExactSignature_aOaA0_TzBY0_fid2() {
    byte[] signature = {(byte) 0xCA, (byte) 0xFE, (byte) 0xDA, (byte) 0x0D};
    int length = 4;
    assertFalse(Pack200CompressorInputStream.matches(signature, length));
}
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
public void testMatches_LongerSignatureCorrectStart_ViyA3_Aaqx0_fid2() {
    byte[] signature = {(byte) 0xCA, (byte) 0xFE, (byte) 0xDA, (byte) 0x0D, (byte) 0x01, (byte) 0x02};
    int length = 6;
    assertFalse(Pack200CompressorInputStream.matches(signature, 4));
}
}