/**
 * Generated by Aster
 */
package org.apache.commons.compress.compressors.lz77support;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class ASTER_LZ77Compressor_Test_Passing {
}