/**
 * Generated by Aster
 */
package org.apache.commons.codec.binary;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

public class ASTER_Base16_Coverage_Test_Failing {
    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDecodeOffsetLessThanEnd_evQG10_FaUJ0() {
        Base16 base16 = new Base16();
        Base16.Context context = new Base16.Context();
        byte[] data = new byte[]{0x30, 0x31};
        base16.decode(data, 0, 2, context);
        assertEquals(2, context.ibitWorkArea);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDecodeOffsetLessThanEnd_evQG10_FaUJ0_fid1() {
        Base16 base16 = new Base16();
        Base16.Context context = new Base16.Context();
        byte[] data = new byte[]{0x30, 0x31};
        base16.decode(data, 0, 0, context);
        assertEquals(2, context.ibitWorkArea);
    }
}